name: "Build Game Artifact"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GODOT_VERSION: 3.2.3
  EXECUTABLE_TITLE: moonshot
  SOURCE_DIRECTORY: src

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        lfs:
          default: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $SOURCE_DIRECTORY
          godot -v --export "Windows Desktop" ../build/windows/$EXECUTABLE_TITLE-$(echo ${GITHUB_SHA} | cut -c1-6).exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-$EXECUTABLE_TITLE-$(echo ${GITHUB_SHA} | cut -c1-6)
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        lfs:
          default: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $SOURCE_DIRECTORY
          godot -v --export "Linux/X11" ../build/linux/$EXECUTABLE_TITLE-$(echo ${GITHUB_SHA} | cut -c1-6).x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux-$EXECUTABLE_TITLE-$(echo ${GITHUB_SHA} | cut -c1-6)
          path: build/linux
